version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_HOST=localhost
      - DATABASE_PORT=5432
      - DATABASE_USERNAME=postgres
      - DATABASE_PASSWORD=postgres
      - DATABASE_NAME=test_team
      - DATABASE_SYNC=false
      - DATABAE_SSL=true
      - SERVER_PORT=3000
      - JWT_SECRET="password123"
      - JWT_ACCESS_TOKEN_EXPIRESIN=3h
    depends_on:
      - postgres
  frontend:
  postgres:
  nginx: