version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_USERNAME: mohaned
      DATABASE_PASSWORD: password123
      DATABASE_NAME: test_team
      DATABASE_SYNC: true
      DATABASE_SSL: false
      SERVER_PORT: 3000
      SERVER_FRONTEND_URL: frontend:8080
      JWT_SECRET: password123
      JWT_ACCESS_TOKEN_EXPIRESIN: 3h
      USER_PASSWORD_SOLT_RANGE: 12
    depends_on:
      - postgres
  frontend:
    build: ./frontend
    depends_on:
      - backend
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: mohaned
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: test_team
    volumes:
      - ./pgdata:/var/lib/postgresql/data
  nginx:
    image: nginx:alpine
    ports:
      - "8080:8080"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - frontend